export const AMAZON_ACTION_POLICY = {
  AUTO_HANDLE: [
    "ORDER_STATUS",
    "PRIME_MEMBERSHIP",
    "PRIME_VIDEO",
    "PRODUCT_DEVICE_SUPPORT",
    "OTHER_SUPPORT",
  ],

  ESCALATE: [
    "ACCOUNT_ACCESS",
    "PAYMENT_BILLING",
    "RETURNS_REFUNDS",
    "ORDER_CANCELLATION",
    "ORDER_DELIVERY",
  ],
} as const;